import spryvmtest
import sprycoretest
import sprymathtest
import sprystringtest
import spryblocktest
import spryootest
#import spryiotest
#import spryostest
import spryreflecttest
#import sprycompresstest
#import sprymemfiletest
import spryextendtest
